name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - uses: nrwl/nx-set-shas@v3

      - run: yarn install --frozen-lockfile --immutable

      - run: yarn nx workspace-lint

      - run: yarn nx format:check

      - run: yarn nx affected --target=lint --parallel=3

      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage --detectOpenHandles

      - run: yarn nx affected --target=build --parallel=3

      - run: yarn nx run documentation:export

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: dist/apps/documentation/exported
          retention-days: "5"

  e2e:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.18.0-chrome107-ff106-edge

    strategy:
      fail-fast: false
      matrix:
        # 'containers' is a placeholder variable to create extra machines for parallel execution
        containers: [1, 2, 3]
        # 'browser' provides runners for each browser that will be tested
        browser:
          - chrome
          # - electron
          # - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          install: false
          record: true
          parallel: true
          group: 3x-${{ matrix.browser }}
          command: yarn nx e2e documentation-e2e -- -- --record --group 3x-${{ matrix.browser }} --parallel
        env:
          CYPRESS_VIDEO: false
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: 15000
          CYPRESS_PROJECT_ID: y8kvbv
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-artifacts-${{ matrix.browser }}
          if-no-files-found: ignore
          path: dist/cypress/apps/documentation-e2e

  # Deploy documentation to GitHub Pages
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    concurrency:
      group: pages
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
